apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  namespace: jenkins-ns
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_ACCESS_KEY_ID
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-credentials
          key: AWS_SECRET_ACCESS_KEY
    volumeMounts:
      - name: aws-config
        mountPath: /kaniko/.aws
  volumes:
    - name: aws-config
      secret:
        secretName: aws-credentials